services:
  skills:
    image: uchile_robotics/skills
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skills
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    # devices:
      # - host:container
    # volumes:
      # - hostPath:containerPath:ro
    