services:
  jaime_core:
    image: uchile_robotics/jaime_core
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaime_core
    network_mode: host
    devices:
      - /dev/rplidar:/dev/rplidar
      - /dev/pioneer:/dev/pioneer
      - /dev/input/js0:/dev/input/js0
      - /dev/input/event28:/dev/input/event28
    volumes:
      - ~/uchile_robotics/jaime_bringup:/home/jaime_ws/src/jaime_bringup
      - ~/uchile_robotics/jaime_core:/home/jaime_ws/src/jaime_core
      - ~/uchile_robotics/uchile_high:/home/jaime_ws/src/uchile_high
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    stdin_open: true
    tty: true
