sudo apt-get install ros-melodic-octomap-msgs
sudo apt-get install ros-melodic-naoqi-libqi
sudo apt-get install ros-melodic-naoqi-libcore
sudo apt-get install ros-melodic-ecl-build
sudo apt-get install ros-melodic-ecl-threads
sudo apt-get install ros-melodic-ecl
sudo apt-get install ros-melodic-bfl
sudo apt-get install ros-melodic-laser-proc
sudo apt-get install ros-melodic-urg-c
sudo apt-get install ros-melodic-tf2-sensor-msgs
sudo apt-get install ros-melodic-rosserial-arduino
sudo apt-get install ros-melodic-joy
sudo apt-get install ros-melodic-sound-play
sudo apt-get install ros-melodic-qt-build
sudo apt-get install ros-melodic-effort-controllers
sudo apt-get install ros-melodic-moveit
sudo apt-get install ros-melodic-rviz-visual-tools
sudo apt-get install ros-melodic-openni2-camera
sudo apt-get install ros-melodic-move-base