#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Adaptado de:
# http://mediadoneright.com/content/ultimate-git-ps1-bash-prompt
#
# En la misma página salen más muuuuchos más colores y como agregar la hora
# - - - - - - parameters - - - - - 
PathShort="\w"
Green="\[\033[0;32m\]"        # Green
White="\[\033[0;37m\]"        # White
IRed="\[\033[0;91m\]"         # High Intensty Red
Color_Off="\[\033[0m\]"       # Text Color Reset

# export prompt
export PS1='\u@\h:'$White$PathShort$Color_Off'$(git branch &>/dev/null;\
if [ $? -eq 0 ]; then \
  echo "$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; \
  if [ "$?" -eq "0" ]; then \
    # @4 - Clean repository - nothing to commit
    echo "'$Green'"$(__git_ps1 " (%s)"); \
  else \
    # @5 - Changes to working tree
    echo "'$IRed'"$(__git_ps1 " {%s}"); \
  fi) '$Color_Off'\$ "; \
else \
  # @2 - Prompt when not in GIT repo
  echo "'$Color_Off'\$ "; \
fi)'
