services:
  rosaria2_container:
    image: rosaria2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bender_container
    network_mode: host
    devices:
      - /dev/rplidar:/dev/rplidar
      - /dev/pioneer:/dev/pioneer
      - /dev/input/js0:/dev/input/js0
      - /dev/input/event258:/dev/input/event258
    volumes:
      - ~/bender_bringup:/home/base_controller/src/bender_bringup
      - ~/bender_core:/home/base_controller/src/bender_core
      - ~/.docker-github-netrc:/root/.netrc:ro
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    stdin_open: true
    tty: true
