services:
  bender_core:
    image: uchile_robotics/bender_core
    build:
      context: ./core/
      dockerfile: Dockerfile
    network_mode: host
    container_name: bender_core
    devices:
      - /dev/rplidar:/dev/rplidar
      - /dev/pioneer:/dev/pioneer
      - /dev/joy:/dev/joy
      - /dev/event_joy:/dev/event_joy
    volumes:
      - ~/uchile_robotics/bender_bringup:/home/bender_ws/src/bender_bringup
      - ~/uchile_robotics/bender_core:/home/bender_ws/src/bender_core
      - ~/uchile_robotics/uchile_navigation:/home/bender_ws/src/uchile_navigation
      - ~/uchile_robotics/uchile_high:/home/bender_ws/src/uchile_high
    working_dir: /home/bender_ws
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    stdin_open: true
    tty: true

  skills:
    image: uchile_robotics/skills
    build:
      context: ./skills/
      dockerfile: Dockerfile
    container_name: skills
    network_mode: host
    working_dir: /home/bender_ws
    volumes:
      - ~/uchile_robotics/uchile_common:/home/bender_ws/src/uchile_common
      - ~/uchile_robotics/uchile_high:/home/bender_ws/src/uchile_high
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    # devices:
      # - host:container
    # volumes:
      # - hostPath:containerPath:ro
    
